/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mylp_activityone_MyButtonListener */

#ifndef _Included_com_mylp_activityone_MyButtonListener
#define _Included_com_mylp_activityone_MyButtonListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
