/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mylp_activityone */

#ifndef _Included_com_mylp_activityone
#define _Included_com_mylp_activityone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mylp_activityone
 * Method:    sgtba
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtba
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbb
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbb
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbc
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbd
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbe
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbe
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbf
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbf
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbg
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbh
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbh
  (JNIEnv *, jobject);

/*
 * Class:     com_mylp_activityone
 * Method:    sgtbi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_activityone_sgtbi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
