/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mylp_amyluoactivity */

#ifndef _Included_com_mylp_amyluoactivity
#define _Included_com_mylp_amyluoactivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mylp_amyluoactivity
 * Method:    pstr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mylp_amyluoactivity_pstr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
